spring.application.name=language
spring.datasource.url=jdbc:mysql://mysql.llam.tec.br:3306/MediaVitae
spring.datasource.username=root
spring.datasource.password=8784789;

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


